# Generated by Django 3.1 on 2021-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nzapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=800)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
