# Generated by Django 3.1 on 2021-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nzapp', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
