# Generated by Django 3.1 on 2021-02-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nzapp', '0003_auto_20210210_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
