# Generated by Django 3.1 on 2021-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nzapp', '0004_auto_20210210_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
